export const MenuCoffee = [
  {
    id: 'Expresso Tradicional',
    name: 'Expresso Tradicional',
    amount: 0,
    description: 'O tradicional café feito com água quente e grãos moídos',
    price: 9.99,
    image: 'Expresso',
    tags: ['Tradicional'],
  },
  {
    id: 'Expresso Americano',
    name: 'Expresso Americano',
    amount: 0,
    description: 'Expresso diluído, menos intenso que o tradicional',
    price: 9.99,
    image: 'Americano',
    tags: ['Tradicional'],
  },
  {
    id: 'Expresso Cremoso',
    name: 'Expresso Cremoso',
    amount: 0,
    description: 'Café expresso tradicional com espuma cremosa',
    price: 9.99,
    image: 'Expresso Cremoso',
    tags: ['Tradicional'],
  },
  {
    id: 'Expresso Gelado',
    name: 'Expresso Gelado',
    amount: 0,
    description: 'Bebida preparada com café expresso e cubos de gelo',
    price: 9.99,
    image: 'Café Gelado',
    tags: ['Tradicional', 'gelado'],
  },
  {
    id: 'Café com Leite',
    name: 'Café com Leite',
    amount: 0,
    description: 'Meio a meio de expresso tradicional com leite vaporizado',
    price: 9.99,
    image: 'Café com Leite',
    tags: ['Tradicional', 'com leite'],
  },
  {
    id: 'Latte',
    name: 'Latte',
    amount: 0,
    description:
      'Uma dose de café expresso com o dobro de leite e espuma cremosa',
    price: 9.99,
    image: 'Latte',
    tags: ['Tradicional', 'com leite'],
  },
  {
    id: 'Capuccino',
    name: 'Capuccino',
    amount: 0,
    description:
      'Bebida com canela feita de doses iguais de café, leite e espuma',
    price: 9.99,
    image: 'Capuccino',
    tags: ['Tradicional', 'com leite'],
  },
  {
    id: 'Macchiato',
    name: 'Macchiato',
    amount: 0,
    description:
      'Café expresso misturado com um pouco de leite quente e espuma',
    price: 9.99,
    image: 'Macchiato',
    tags: ['Tradicional', 'com leite'],
  },
  {
    id: 'Mocaccino',
    name: 'Mocaccino',
    amount: 0,
    description: 'Café expresso com calda de chocolate, pouco leite e espuma',
    price: 9.99,
    image: 'Mocaccino',
    tags: ['Tradicional', 'com leite'],
  },
  {
    id: 'Chocolate Quente',
    name: 'Chocolate Quente',
    amount: 0,
    description: 'Bebida feita com chocolate dissolvido no leite quente e café',
    price: 9.99,
    image: 'Chocolate Quente',
    tags: ['especial', 'com leite'],
  },
  {
    id: 'Cubano',
    name: 'Cubano',
    amount: 0,
    description:
      'Drink gelado de café expresso com rum, creme de leite e hortelã',
    price: 9.99,
    image: 'Cubano',
    tags: ['especial', 'alcoólico', 'gelado'],
  },
  {
    id: 'Havaiano',
    name: 'Havaiano',
    amount: 0,
    description: 'Bebida adocicada preparada com café e leite de coco',
    price: 9.99,
    image: 'Havaiano',
    tags: ['especial'],
  },
  {
    id: 'Árabe',
    name: 'Árabe',
    amount: 0,
    description: 'Bebida preparada com grãos de café árabe e especiarias',
    price: 9.99,
    image: 'Árabe',
    tags: ['especial'],
  },
  {
    id: 'Irlandês',
    name: 'Irlandês',
    amount: 0,
    description: 'Bebida a base de café, uísque irlandês, açúcar e chantilly',
    price: 9.99,
    image: 'Irlandês',
    tags: ['especial', 'alcoólico'],
  },
]
